max_time_step = 0.001
number_of_steps = 100_000
write_step = 1000
dist_threshold = 0.01

bodies = [
    { mass = 0.3, pos = [1.0, 0.0], vel = [0.0, 0.011] },
    { mass = 0.2, pos = [-0.5, -1.5], vel = [0.02, -0.015] },
    { mass = 0.2, pos = [0.0, 1.0], vel = [-0.035, 0.0] }
]
